### ISSUE TITLE
UI: Balances

### ISSUE THREAD

**Issue by dexX7** [zathras-crypto/omnicore#16] opened 2015-02-12 06:17 UTC
![2_balances](https://cloud.githubusercontent.com/assets/5836089/6162617/9546b216-b286-11e4-9679-ef22752933cc.png)
- [ ] 2) Highest priority: right-click -> "copy address" or "send from this address" **Edit: UI 0.0.9.2 #33**
- [x] 3) The behavior of resizing the colums feels very odd, and the seperator between "address" and "reserved" can't be moved.
- [ ] 4) Sorting columns, similar to the Bitcoin transaction histoy would be great. **Edit: UI 0.0.9.2 #32**
- [x] 5) ~~I'm not sure about it, but my first impression was that "available" should be left to "reserved". This is very vague though.~~ edit: too vague and probably wrong anyway

**Comment by dexX7** [comment] 2015-02-12 07:01
Regarding 3, here is an example where not the full balance is visible, because the width of "available" can't be increased:

![3_send_1](https://cloud.githubusercontent.com/assets/5836089/6163065/4007a6be-b28d-11e4-978e-ae025f3fa454.png)

**Comment by zathras-crypto** [comment] 2015-02-12 07:21
Increase 'Available' with the adjuster on the right of the column header -
agreed seems un-intuitive - on the todo list :)

**Comment by zathras-crypto** [comment] 2015-02-13 00:50
Regarding 2) - I understand the value in 'send from this address' but 'copy address' is of little use in sending (you can't paste into 'send from' in the send dialog) - shame because that's the easier of the two to implement hehe...  Let me investigate this one

**Comment by zathras-crypto** [comment] 2015-02-13 03:17
Some things I'd like to defer to a 0.0.9.2 UI release (which can come soon, won't be a required upgrade) so could you do me a favour? For new issues please address one item per issue - then I can use a few labels I just created to categorize into quick items I can do for 0.0.9.1 and other items I'll defer to next minor release.

**Comment by zathras-crypto** [comment] 2015-02-13 03:20
2/4 likely defer to 0.0.9.2
3 will address for 0.0.9.1

**Comment by dexX7** [comment] 2015-02-13 03:24
> 'copy address' is of little use

Consistency is also important in my opinion, and it's available basically everywhere else where addresses are involved.

I see the dilemma though, given that the combobox is either readonly and it's not possible to paste values into it, or it's fully editable and probably no way to handle the input properly, I assume.

> For new issues please address one item per issue

Yes, very good idea. I started with the screenshots, then had the idea with the issues and check marks, and this is the perfect extension of it. :)

**Comment by zathras-crypto** [comment] 2015-02-13 22:44
Just a quick note to say still working on the balances stuff.  Basically the issue is that when using QHeaderView::Stretch or QHeaderView::ResizeToContents these block user resizing of the columns.  So I'm now using QHeaderView::Interactive on everything and resizing in code which provides the required movements, but making the stretch manually is awkward and is lost obviously when window is resized.  I'm trying to reuse some stuff from GUIUtil that the Bitcoin guys use, but most of that functionality is hardcoded for the Bitcoin tx history column layout (specifically always stretching 2nd to last column which doesn't work for us).  My own implementation of that sadly segfaulted due to the way I'd overridden the resize and paint events of the form and it was getting kind of hacky.  Anyway just a quick update, still working on it, currently moving to a model where I reuse same functions in GUIUtil at the way the bitcoin guys do it but I modify them to be adaptable to different column layouts.  Will let you know when I have something working to commit :)

Thanks
Z

**Comment by zathras-crypto** [comment] 2015-02-14 09:13
OK, give https://github.com/zathras-crypto/mastercore/commit/8bfb0d3739b28e849a374491f2ed28501a09c024 a whirl and let me know what you think.

Thanks
Z

**Comment by dexX7** [comment] 2015-02-14 09:39
Haha this is so much better, thanks a lot! :) Last note for this page: "available" and "reserved" should be right, not left aligned in my opinon.

**Comment by zathras-crypto** [comment] 2015-02-14 09:40
Great :) Re right aligned numbers, yep oversight will fix that should be easy enough :)

**Comment by zathras-crypto** [comment] 2015-02-14 10:17
Right align amounts on balances tab https://github.com/zathras-crypto/mastercore/commit/b0b923145c55a521a641c7cf1e16345b1ac989e1

Thanks
Z

**Closed as completed** 2015-02-16 15:47 UTC
Labels: feature requests - 0.0.9.1, ready to close
