### ISSUE TITLE
UI: Transactions

### ISSUE THREAD

**Issue by dexX7** [zathras-crypto/omnicore#18] opened 2015-02-12 06:27 UTC
![4_transactions](https://cloud.githubusercontent.com/assets/5836089/6162787/9b74bc62-b288-11e4-89eb-329fbea39a3b.png)
- [x] 9) Sorting columns would be nice here as well. **Edit: UI 0.0.9.2 #31**
- [x] 10) The seperator between "address" and "amount" can't be moved.
- [x] 11) When resizing the first column over some threshold, it can never get smaller than shown.

**Comment by zathras-crypto** [comment] 2015-02-13 03:26
9 deferring to 0.0.9.2
10/11 will address for 0.0.9.1

**Comment by dexX7** [comment] 2015-02-14 09:45
Did you somehow fix point 11 by any chance? I'm unable to reproduce it with the new build, but wasn't aware you addressed this already.

**Comment by zathras-crypto** [comment] 2015-02-14 09:53
It's still reproducible for me, I'd taken a quick look but not committed any fix for it - the culprit is this appears when you expand the column (and you can then no longer shrink past it):
![image](https://cloud.githubusercontent.com/assets/5633351/6199238/7c147466-b48b-11e4-9758-12e98c656c2a.png)
Items for this issue are next on my list :)

**Comment by dexX7** [comment] 2015-02-14 09:59
Yes, this is what I experienced as well, but now I'm it always works fine, for some reason.

**Comment by zathras-crypto** [comment] 2015-02-15 23:37
Still working 10 :( issue here is that I use a hidden column to store the TXID which is making a mess again of the stuff I'm borrowing from GUIUtil...  Always alignment and interface that slows you down! hehe

11 was easy since that column doesn't really need to be resized so we can just set it to 'fixed' so it's not resizeable.

**Comment by zathras-crypto** [comment] 2015-02-16 05:53
My eyes going square :P

![image](https://cloud.githubusercontent.com/assets/5633351/6207669/30dc0ff0-b5fc-11e4-8499-b140f6dbeb1c.png)

**Comment by zathras-crypto** [comment] 2015-02-16 05:57
And the fix (hopefully).

EDIT: would help if I actually linked the commit hehe...
https://github.com/zathras-crypto/mastercore/commit/e40b625f4fdda38119b45a340bdd05ad8cbbd793

And then cleanup + bugfix:
https://github.com/zathras-crypto/mastercore/commit/9b4d689e4c6ad003e7384980fcbb0369c0fb4449
https://github.com/zathras-crypto/mastercore/commit/7aa59302fba80052343aacb9a831ab01ecc8eeab

**Comment by dexX7** [comment] 2015-02-16 15:37
Works perfect for me!

**Closed as completed** 2015-02-16 15:43 UTC
Labels: improvement - 0.0.9.1, ready to close
